name: "Test"

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]

jobs:
  test-stable:
    name: "Test stable toolchain"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        if: matrix.info.container == ''
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Enable Rust cache
        uses: Swatinem/rust-cache@6fd3edff6979b79f87531400ad694fb7f2c84b1f # 2.2.1
        with:
          cache-on-failure: true
          workspaces: "./test/hello_world -> target"

      - name: Test simple
        uses: ./
        with:
          command: build
          directory: test/hello_world

      - name: Test args
        uses: ./
        with:
          command: build
          args: --release
          directory: test/hello_world

  test-nightly:
    name: "Test nightly toolchain"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        if: matrix.info.container == ''
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Enable Rust cache
        uses: Swatinem/rust-cache@22c9328bcba27aa81a32b1bef27c7e3c78052531 # 2.0.1
        with:
          cache-on-failure: true
          workspaces: "./test/hello_world -> target"

      - name: Test simple
        uses: ./
        with:
          toolchain: nightly
          command: build
          directory: test/hello_world

      - name: Test args
        uses: ./
        with:
          toolchain: nightly
          command: build
          args: --release
          directory: test/hello_world

  test-cross:
    name: "Test using cross"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        if: matrix.info.container == ''
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu

      - name: Enable Rust cache
        uses: Swatinem/rust-cache@22c9328bcba27aa81a32b1bef27c7e3c78052531 # 2.0.1
        with:
          cache-on-failure: true
          workspaces: "./test/hello_world -> target"

      - name: Test args
        uses: ./
        with:
          command: build
          args: --target aarch64-unknown-linux-gnu
          use-cross: true
          cross-version: 0.2.4
          directory: test/hello_world

      - name: Test persisting install
        uses: ./
        with:
          command: build
          args: --release --target aarch64-unknown-linux-gnu
          use-cross: true
          cross-version: 0.2.4
          directory: test/hello_world
